### ISSUE TITLE
run/install error

### ISSUE THREAD

**Issue by priest1234** [goofcc/gorevel#3]
ERROR 2014/12/29 09:38:40 build.go:98: github.com\disintegration\imaging\helpers .go:28:2: cannot find package "golang.org/x/image/bmp"

ERROR 2014/12/29 09:39:22 build.go:118: package golang.org/x/image/bmp: unrecognized import path "golang.org/x/image/bmp"

**Comment by onlyeat3** [comment]
同样是遇见了安装错误，可有好办法对付第三方包下载的问题？

**Comment by goofcc** [comment]
这些被 墙的包在 github.com/golang 上都有镜像，可以用 git clone 到 GOPATH/src/golang.org/x/...
具体包名改下就可以了
